In [1]:
import recipe

In [7]:
recipe.main()

=== Recipe Manager===
1. Add a new recipe to the collection
2. Search for recipes by ingredient
3. View all recipes
4. View a random recipe suggestion
5. Exit

Enter your choice (1-5):  1
Enter the recipe category(Breakfast, Lunch, Dinner, Dessert) bacha

Please type Breakfast, Lunch, Dinner or Dessert.

Enter the recipe category(Breakfast, Lunch, Dinner, Dessert) dinner
Enter the recipe name bacha
Enter the ingredients (separated by commas):  meat,salt,pepper,water,bread
Enter the preperation time in minuts 120
Enter the cooking instructions cut the bread into small pieces
Enter the difficulty (Easy, Medium, Hard) medium

recipies has been updated!

=== Recipe Manager===
1. Add a new recipe to the collection
2. Search for recipes by ingredient
3. View all recipes
4. View a random recipe suggestion
5. Exit

Enter your choice (1-5):  1
Enter the recipe category(Breakfast, Lunch, Dinner, Dessert) lunch
Enter the recipe name mandi
Enter the ingredients (separated by commas):  rice,chicken/meat,salt,garlic,tomato paste,water
Enter the preperation time in minuts 120
Enter the cooking instructions
Enter the difficulty (Easy, Medium, Hard) hard

recipies has been updated!

=== Recipe Manager===
1. Add a new recipe to the collection
2. Search for recipes by ingredient
3. View all recipes
4. View a random recipe suggestion
5. Exit

Enter your choice (1-5):  5

Thank you for using Recipe manager. Goodbye!

In [5]:
recipe.view_all()

  recipe_name  prep_time
0    omelette         10

In [8]:
recipe.search_by_ingredient()

Enter an ingredient:  meat

Recipes containing 'meat':

,category,recipe_name,ingredients,prep_time,instruction,Difficulty
1,dinner,bacha,"['meat', 'salt', 'pepper', 'water', 'bread']",120,cut the bread into small pieces,medium
2,lunch,mandi,"['rice', 'chicken/meat', 'salt', 'garlic', 'to...",120,NaN,hard